/****************************************************************************
**
** Metadata for AXIMAGELib generated by dumpcpp v5.12.2 using
** dumpcpp.exe {4FED1AC3-6CF3-11D6-BB83-9FDD9223647D}
** from the type library C:\WINDOWS\SysWow64\AxImage.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_AXIMAGELIB_NOINLINES
#include "aximagelib.h"

using namespace AXIMAGELib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[136];
    char stringdata0[1242];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 21, 0),
QT_MOC_LITERAL(1, 22, 16, 0),
QT_MOC_LITERAL(2, 39, 0, 0),
QT_MOC_LITERAL(3, 40, 9, 0),
QT_MOC_LITERAL(4, 50, 9, 0),
QT_MOC_LITERAL(5, 60, 4, 0),
QT_MOC_LITERAL(6, 65, 6, 0),
QT_MOC_LITERAL(7, 72, 4, 0),
QT_MOC_LITERAL(8, 77, 4, 0),
QT_MOC_LITERAL(9, 82, 15, 0),
QT_MOC_LITERAL(10, 98, 4, 0),
QT_MOC_LITERAL(11, 103, 6, 0),
QT_MOC_LITERAL(12, 110, 4, 0),
QT_MOC_LITERAL(13, 115, 4, 0),
QT_MOC_LITERAL(14, 120, 5, 0),
QT_MOC_LITERAL(15, 126, 3, 0),
QT_MOC_LITERAL(16, 130, 8, 0),
QT_MOC_LITERAL(17, 139, 3, 0),
QT_MOC_LITERAL(18, 143, 3, 0),
QT_MOC_LITERAL(19, 147, 12, 0),
QT_MOC_LITERAL(20, 160, 6, 0),
QT_MOC_LITERAL(21, 167, 5, 0),
QT_MOC_LITERAL(22, 173, 6, 0),
QT_MOC_LITERAL(23, 180, 3, 0),
QT_MOC_LITERAL(24, 184, 16, 0),
QT_MOC_LITERAL(25, 201, 6, 0),
QT_MOC_LITERAL(26, 208, 16, 0),
QT_MOC_LITERAL(27, 225, 6, 0),
QT_MOC_LITERAL(28, 232, 4, 0),
QT_MOC_LITERAL(29, 237, 4, 0),
QT_MOC_LITERAL(30, 242, 3, 0),
QT_MOC_LITERAL(31, 246, 5, 0),
QT_MOC_LITERAL(32, 252, 6, 0),
QT_MOC_LITERAL(33, 259, 11, 0),
QT_MOC_LITERAL(34, 271, 14, 0),
QT_MOC_LITERAL(35, 286, 6, 0),
QT_MOC_LITERAL(36, 293, 5, 0),
QT_MOC_LITERAL(37, 299, 6, 0),
QT_MOC_LITERAL(38, 306, 6, 0),
QT_MOC_LITERAL(39, 313, 5, 0),
QT_MOC_LITERAL(40, 319, 6, 0),
QT_MOC_LITERAL(41, 326, 4, 0),
QT_MOC_LITERAL(42, 331, 6, 0),
QT_MOC_LITERAL(43, 338, 7, 0),
QT_MOC_LITERAL(44, 346, 7, 0),
QT_MOC_LITERAL(45, 354, 4, 0),
QT_MOC_LITERAL(46, 359, 6, 0),
QT_MOC_LITERAL(47, 366, 12, 0),
QT_MOC_LITERAL(48, 379, 8, 0),
QT_MOC_LITERAL(49, 388, 9, 0),
QT_MOC_LITERAL(50, 398, 14, 0),
QT_MOC_LITERAL(51, 413, 12, 0),
QT_MOC_LITERAL(52, 426, 12, 0),
QT_MOC_LITERAL(53, 439, 12, 0),
QT_MOC_LITERAL(54, 452, 10, 0),
QT_MOC_LITERAL(55, 463, 15, 0),
QT_MOC_LITERAL(56, 479, 5, 0),
QT_MOC_LITERAL(57, 485, 14, 0),
QT_MOC_LITERAL(58, 500, 13, 0),
QT_MOC_LITERAL(59, 514, 1, 0),
QT_MOC_LITERAL(60, 516, 1, 0),
QT_MOC_LITERAL(61, 518, 13, 0),
QT_MOC_LITERAL(62, 532, 13, 0),
QT_MOC_LITERAL(63, 546, 13, 0),
QT_MOC_LITERAL(64, 560, 7, 0),
QT_MOC_LITERAL(65, 568, 8, 0),
QT_MOC_LITERAL(66, 577, 7, 0),
QT_MOC_LITERAL(67, 585, 7, 0),
QT_MOC_LITERAL(68, 593, 9, 0),
QT_MOC_LITERAL(69, 603, 10, 0),
QT_MOC_LITERAL(70, 614, 10, 0),
QT_MOC_LITERAL(71, 625, 11, 0),
QT_MOC_LITERAL(72, 637, 11, 0),
QT_MOC_LITERAL(73, 649, 9, 0),
QT_MOC_LITERAL(74, 659, 8, 0),
QT_MOC_LITERAL(75, 668, 7, 0),
QT_MOC_LITERAL(76, 676, 5, 0),
QT_MOC_LITERAL(77, 682, 8, 0),
QT_MOC_LITERAL(78, 691, 4, 0),
QT_MOC_LITERAL(79, 696, 8, 0),
QT_MOC_LITERAL(80, 705, 9, 0),
QT_MOC_LITERAL(81, 715, 10, 0),
QT_MOC_LITERAL(82, 726, 3, 0),
QT_MOC_LITERAL(83, 730, 4, 0),
QT_MOC_LITERAL(84, 735, 6, 0),
QT_MOC_LITERAL(85, 742, 8, 0),
QT_MOC_LITERAL(86, 751, 7, 0),
QT_MOC_LITERAL(87, 759, 8, 0),
QT_MOC_LITERAL(88, 768, 4, 0),
QT_MOC_LITERAL(89, 773, 4, 0),
QT_MOC_LITERAL(90, 778, 4, 0),
QT_MOC_LITERAL(91, 783, 6, 0),
QT_MOC_LITERAL(92, 790, 5, 0),
QT_MOC_LITERAL(93, 796, 9, 0),
QT_MOC_LITERAL(94, 806, 10, 0),
QT_MOC_LITERAL(95, 817, 11, 0),
QT_MOC_LITERAL(96, 829, 4, 0),
QT_MOC_LITERAL(97, 834, 12, 0),
QT_MOC_LITERAL(98, 847, 9, 0),
QT_MOC_LITERAL(99, 857, 6, 0),
QT_MOC_LITERAL(100, 864, 8, 0),
QT_MOC_LITERAL(101, 873, 6, 0),
QT_MOC_LITERAL(102, 880, 13, 0),
QT_MOC_LITERAL(103, 894, 9, 0),
QT_MOC_LITERAL(104, 904, 5, 0),
QT_MOC_LITERAL(105, 910, 14, 0),
QT_MOC_LITERAL(106, 925, 14, 0),
QT_MOC_LITERAL(107, 940, 1, 0),
QT_MOC_LITERAL(108, 942, 11, 0),
QT_MOC_LITERAL(109, 954, 10, 0),
QT_MOC_LITERAL(110, 965, 3, 0),
QT_MOC_LITERAL(111, 969, 7, 0),
QT_MOC_LITERAL(112, 977, 15, 0),
QT_MOC_LITERAL(113, 993, 5, 0),
QT_MOC_LITERAL(114, 999, 13, 0),
QT_MOC_LITERAL(115, 1013, 13, 0),
QT_MOC_LITERAL(116, 1027, 13, 0),
QT_MOC_LITERAL(117, 1041, 10, 0),
QT_MOC_LITERAL(118, 1052, 7, 0),
QT_MOC_LITERAL(119, 1060, 13, 0),
QT_MOC_LITERAL(120, 1074, 13, 0),
QT_MOC_LITERAL(121, 1088, 7, 0),
QT_MOC_LITERAL(122, 1096, 3, 0),
QT_MOC_LITERAL(123, 1100, 7, 0),
QT_MOC_LITERAL(124, 1108, 14, 0),
QT_MOC_LITERAL(125, 1123, 9, 0),
QT_MOC_LITERAL(126, 1133, 9, 0),
QT_MOC_LITERAL(127, 1143, 6, 0),
QT_MOC_LITERAL(128, 1150, 6, 0),
QT_MOC_LITERAL(129, 1157, 9, 0),
QT_MOC_LITERAL(130, 1167, 5, 0),
QT_MOC_LITERAL(131, 1173, 7, 0),
QT_MOC_LITERAL(132, 1181, 19, 0),
QT_MOC_LITERAL(133, 1201, 17, 0),
QT_MOC_LITERAL(134, 1219, 15, 0),
QT_MOC_LITERAL(135, 1235, 5, 0)
    },
    "AXIMAGELib::_DAxImage\0BackColorChanged\0\0BackColor\0exception\0code\0source\0disc\0"
    "help\0propertyChanged\0name\0signal\0argc\0argv\0Clear\0val\0Colorize\0hue\0sat\0"
    "CopyToHandle\0Create\0width\0height\0bpp\0CreateFromBitmap\0bitmap\0CreateFromHandle\0"
    "handle\0Crop\0left\0top\0right\0bottom\0DecreaseBpp\0errordiffusion\0Dilate\0Ksize\0"
    "Dither\0method\0Erode\0Filter\0int&\0kernel\0Kfactor\0Koffset\0Flip\0GetBpp\0GetColorType\0"
    "GetFrame\0GetHeight\0GetJpegQuality\0GetLastError\0GetNumColors\0GetNumFrames\0"
    "GetPalette\0GetPaletteColor\0index\0GetPaletteSize\0GetPixelColor\0x\0y\0GetPixelIndex\0"
    "GetTransColor\0GetTransIndex\0GetType\0GetWidth\0GetXDPI\0GetYDPI\0GrayScale\0"
    "HuePalette\0correction\0IncreaseBpp\0IsGrayScale\0IsIndexed\0IsInside\0IsValid\0"
    "Light\0contrast\0Load\0FileName\0ImageType\0MakeBitmap\0hdc\0Mean\0Mirror\0Negative\0"
    "Refresh\0Resample\0newx\0newy\0fast\0Rotate\0angle\0Rotate180\0RotateLeft\0RotateRight\0"
    "Save\0SetBackColor\0SetBorder\0Border\0SetFrame\0nFrame\0SetGray8Image\0QVariant&\0"
    "image\0SetGrayPalette\0SetJpegQuality\0q\0SetJpgImage\0SetPalette\0pal\0ncolors\0"
    "SetPaletteIndex\0color\0SetPixelColor\0SetPixelIndex\0SetStdPalette\0SetStretch\0"
    "Stretch\0SetTransColor\0SetTransIndex\0SetXDPI\0dpi\0SetYDPI\0StringToFormat\0"
    "extension\0SwapIndex\0index1\0index2\0Threshold\0level\0control\0AXIMAGELib::AxImage\0"
    "Event Interface 1\0_DAxImageEvents\0Click\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_AXIMAGELib___DAxImage[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    76, 14, // methods
    4, 624, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

// signal: name, argc, parameters, tag, flags
    1, 1, 394, 2, 5,
    4, 4, 397, 2, 5,
    9, 1, 406, 2, 5,
    11, 3, 409, 2, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 416, 2, 9,
    16, 2, 419, 2, 9,
    19, 0, 424, 2, 9,
    20, 3, 425, 2, 9,
    24, 1, 432, 2, 9,
    26, 1, 435, 2, 9,
    28, 4, 438, 2, 9,
    33, 2, 447, 2, 9,
    35, 1, 452, 2, 9,
    37, 1, 455, 2, 9,
    39, 1, 458, 2, 9,
    40, 4, 461, 2, 9,
    45, 0, 470, 2, 9,
    46, 0, 471, 2, 9,
    47, 0, 472, 2, 9,
    48, 0, 473, 2, 9,
    49, 0, 474, 2, 9,
    50, 0, 475, 2, 9,
    51, 0, 476, 2, 9,
    52, 0, 477, 2, 9,
    53, 0, 478, 2, 9,
    54, 0, 479, 2, 9,
    55, 1, 480, 2, 9,
    57, 0, 483, 2, 9,
    58, 2, 484, 2, 9,
    61, 2, 489, 2, 9,
    62, 0, 494, 2, 9,
    63, 0, 495, 2, 9,
    64, 0, 496, 2, 9,
    65, 0, 497, 2, 9,
    66, 0, 498, 2, 9,
    67, 0, 499, 2, 9,
    68, 0, 500, 2, 9,
    69, 1, 501, 2, 9,
    71, 1, 504, 2, 9,
    72, 0, 507, 2, 9,
    73, 0, 508, 2, 9,
    74, 2, 509, 2, 9,
    75, 0, 514, 2, 9,
    76, 2, 515, 2, 9,
    78, 2, 520, 2, 9,
    81, 1, 525, 2, 9,
    83, 0, 528, 2, 9,
    84, 0, 529, 2, 9,
    85, 0, 530, 2, 9,
    86, 0, 531, 2, 9,
    87, 3, 532, 2, 9,
    91, 1, 539, 2, 9,
    93, 0, 542, 2, 9,
    94, 0, 543, 2, 9,
    95, 0, 544, 2, 9,
    96, 2, 545, 2, 9,
    97, 1, 550, 2, 9,
    98, 1, 553, 2, 9,
    100, 1, 556, 2, 9,
    102, 3, 559, 2, 9,
    105, 0, 566, 2, 9,
    106, 1, 567, 2, 9,
    108, 1, 570, 2, 9,
    109, 2, 573, 2, 9,
    112, 2, 578, 2, 9,
    114, 3, 583, 2, 9,
    115, 3, 590, 2, 9,
    116, 0, 597, 2, 9,
    117, 1, 598, 2, 9,
    119, 1, 601, 2, 9,
    120, 1, 604, 2, 9,
    121, 1, 607, 2, 9,
    123, 1, 610, 2, 9,
    124, 1, 613, 2, 9,
    126, 2, 616, 2, 9,
    129, 1, 621, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QColor, 3,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 15,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 17, 18,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 21, 22, 23,
    QMetaType::Int, QMetaType::Int, 25,
    QMetaType::Int, QMetaType::Int, 27,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 29, 30, 31, 32,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 23, 34,
    QMetaType::Bool, QMetaType::Int, 36,
    QMetaType::Bool, QMetaType::Int, 38,
    QMetaType::Bool, QMetaType::Int, 36,
    QMetaType::Bool, 0x80000000 | 41, QMetaType::Int, QMetaType::Int, QMetaType::Int, 42, 36, 43, 44,
    QMetaType::Bool,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::QColor, QMetaType::Int, 56,
    QMetaType::Int,
    QMetaType::QColor, QMetaType::Int, QMetaType::Int, 59, 60,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 59, 60,
    QMetaType::QColor,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Bool,
    QMetaType::Void, QMetaType::Double, 70,
    QMetaType::Bool, QMetaType::Int, 23,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 59, 60,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 76, 77,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 79, 80,
    QMetaType::Int, QMetaType::Int, 82,
    QMetaType::Double,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Int, 88, 89, 90,
    QMetaType::Bool, QMetaType::Double, 92,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 79, 80,
    QMetaType::Void, QMetaType::QColor, 3,
    QMetaType::Void, QMetaType::Bool, 99,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, 0x80000000 | 103, QMetaType::Int, QMetaType::Int, 104, 21, 22,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, 0x80000000 | 103, 104,
    QMetaType::Void, 0x80000000 | 41, QMetaType::Int, 110, 111,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 56, 113,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::QColor, 59, 60, 113,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 59, 60, 56,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 118,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 56,
    QMetaType::Void, QMetaType::Int, 122,
    QMetaType::Void, QMetaType::Int, 122,
    QMetaType::Int, QMetaType::QString, 125,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 127, 128,
    QMetaType::Bool, QMetaType::Int, 130,

 // properties: name, type, flags
    3, QMetaType::QColor, 0x43015003, 		 // QColor BackColor
    99, QMetaType::Bool, 0x01015003, 		 // bool Border
    118, QMetaType::Bool, 0x01015003, 		 // bool Stretch
    131, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DAxImage::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXIMAGELib___DAxImage, 0, 0, 0 }
};

void *_DAxImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXIMAGELib::_DAxImage"))
        return static_cast<void*>(const_cast<_DAxImage*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXIMAGELib__AxImage[] = {

 // content:
    7, // revision
    132,  // classname
    1, 14, // classinfo
    77, 16, // methods
    3, 632, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    5, // signal count

 // classinfo: key, value
    133, 134, 

// signal: name, argc, parameters, tag, flags
    1, 1, 401, 2, 5,
    135, 0, 404, 2, 5,
    4, 4, 405, 2, 5,
    9, 1, 414, 2, 5,
    11, 3, 417, 2, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 424, 2, 9,
    16, 2, 427, 2, 9,
    19, 0, 432, 2, 9,
    20, 3, 433, 2, 9,
    24, 1, 440, 2, 9,
    26, 1, 443, 2, 9,
    28, 4, 446, 2, 9,
    33, 2, 455, 2, 9,
    35, 1, 460, 2, 9,
    37, 1, 463, 2, 9,
    39, 1, 466, 2, 9,
    40, 4, 469, 2, 9,
    45, 0, 478, 2, 9,
    46, 0, 479, 2, 9,
    47, 0, 480, 2, 9,
    48, 0, 481, 2, 9,
    49, 0, 482, 2, 9,
    50, 0, 483, 2, 9,
    51, 0, 484, 2, 9,
    52, 0, 485, 2, 9,
    53, 0, 486, 2, 9,
    54, 0, 487, 2, 9,
    55, 1, 488, 2, 9,
    57, 0, 491, 2, 9,
    58, 2, 492, 2, 9,
    61, 2, 497, 2, 9,
    62, 0, 502, 2, 9,
    63, 0, 503, 2, 9,
    64, 0, 504, 2, 9,
    65, 0, 505, 2, 9,
    66, 0, 506, 2, 9,
    67, 0, 507, 2, 9,
    68, 0, 508, 2, 9,
    69, 1, 509, 2, 9,
    71, 1, 512, 2, 9,
    72, 0, 515, 2, 9,
    73, 0, 516, 2, 9,
    74, 2, 517, 2, 9,
    75, 0, 522, 2, 9,
    76, 2, 523, 2, 9,
    78, 2, 528, 2, 9,
    81, 1, 533, 2, 9,
    83, 0, 536, 2, 9,
    84, 0, 537, 2, 9,
    85, 0, 538, 2, 9,
    86, 0, 539, 2, 9,
    87, 3, 540, 2, 9,
    91, 1, 547, 2, 9,
    93, 0, 550, 2, 9,
    94, 0, 551, 2, 9,
    95, 0, 552, 2, 9,
    96, 2, 553, 2, 9,
    97, 1, 558, 2, 9,
    98, 1, 561, 2, 9,
    100, 1, 564, 2, 9,
    102, 3, 567, 2, 9,
    105, 0, 574, 2, 9,
    106, 1, 575, 2, 9,
    108, 1, 578, 2, 9,
    109, 2, 581, 2, 9,
    112, 2, 586, 2, 9,
    114, 3, 591, 2, 9,
    115, 3, 598, 2, 9,
    116, 0, 605, 2, 9,
    117, 1, 606, 2, 9,
    119, 1, 609, 2, 9,
    120, 1, 612, 2, 9,
    121, 1, 615, 2, 9,
    123, 1, 618, 2, 9,
    124, 1, 621, 2, 9,
    126, 2, 624, 2, 9,
    129, 1, 629, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QColor, 3,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 15,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 17, 18,
    QMetaType::Int,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 21, 22, 23,
    QMetaType::Int, QMetaType::Int, 25,
    QMetaType::Int, QMetaType::Int, 27,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, 29, 30, 31, 32,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 23, 34,
    QMetaType::Bool, QMetaType::Int, 36,
    QMetaType::Bool, QMetaType::Int, 38,
    QMetaType::Bool, QMetaType::Int, 36,
    QMetaType::Bool, 0x80000000 | 41, QMetaType::Int, QMetaType::Int, QMetaType::Int, 42, 36, 43, 44,
    QMetaType::Bool,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::QString,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::QColor, QMetaType::Int, 56,
    QMetaType::Int,
    QMetaType::QColor, QMetaType::Int, QMetaType::Int, 59, 60,
    QMetaType::Int, QMetaType::Int, QMetaType::Int, 59, 60,
    QMetaType::QColor,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Int,
    QMetaType::Bool,
    QMetaType::Void, QMetaType::Double, 70,
    QMetaType::Bool, QMetaType::Int, 23,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 59, 60,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, 76, 77,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 79, 80,
    QMetaType::Int, QMetaType::Int, 82,
    QMetaType::Double,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Void,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Int, 88, 89, 90,
    QMetaType::Bool, QMetaType::Double, 92,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Bool,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, 79, 80,
    QMetaType::Void, QMetaType::QColor, 3,
    QMetaType::Void, QMetaType::Bool, 99,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, 0x80000000 | 103, QMetaType::Int, QMetaType::Int, 104, 21, 22,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 107,
    QMetaType::Void, 0x80000000 | 103, 104,
    QMetaType::Void, 0x80000000 | 41, QMetaType::Int, 110, 111,
    QMetaType::Void, QMetaType::Int, QMetaType::QColor, 56, 113,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::QColor, 59, 60, 113,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, QMetaType::Int, 59, 60, 56,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 118,
    QMetaType::Void, QMetaType::Int, 113,
    QMetaType::Void, QMetaType::Int, 56,
    QMetaType::Void, QMetaType::Int, 122,
    QMetaType::Void, QMetaType::Int, 122,
    QMetaType::Int, QMetaType::QString, 125,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 127, 128,
    QMetaType::Bool, QMetaType::Int, 130,

 // properties: name, type, flags
    3, QMetaType::QColor, 0x43015003, 		 // QColor BackColor
    99, QMetaType::Bool, 0x01015003, 		 // bool Border
    118, QMetaType::Bool, 0x01015003, 		 // bool Stretch

    0 // eod
};

const QMetaObject AxImage::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXIMAGELib__AxImage, 0, 0, 0 }
};

void *AxImage::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXIMAGELib::AxImage"))
        return static_cast<void*>(const_cast<AxImage*>(this));
    return QAxWidget::qt_metacast(_clname);
}

