/****************************************************************************
**
** Metadata for RealSvrOcxTcpLib generated by dumpcpp v5.12.2 using
** dumpcpp.exe {86683A0C-A3FA-4412-B044-51B918DBEE5C}
** from the type library C:\WINDOWS\SysWow64\RealSvrOcxTcp.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_REALSVROCXTCPLIB_NOINLINES
#include "realsvrocxtcplib.h"

using namespace RealSvrOcxTcpLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[42];
    char stringdata0[574];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 33, 0),
QT_MOC_LITERAL(1, 34, 9, 0),
QT_MOC_LITERAL(2, 44, 0, 0),
QT_MOC_LITERAL(3, 45, 4, 0),
QT_MOC_LITERAL(4, 50, 6, 0),
QT_MOC_LITERAL(5, 57, 4, 0),
QT_MOC_LITERAL(6, 62, 4, 0),
QT_MOC_LITERAL(7, 67, 15, 0),
QT_MOC_LITERAL(8, 83, 4, 0),
QT_MOC_LITERAL(9, 88, 6, 0),
QT_MOC_LITERAL(10, 95, 4, 0),
QT_MOC_LITERAL(11, 100, 4, 0),
QT_MOC_LITERAL(12, 105, 8, 0),
QT_MOC_LITERAL(13, 114, 12, 0),
QT_MOC_LITERAL(14, 127, 10, 0),
QT_MOC_LITERAL(15, 138, 11, 0),
QT_MOC_LITERAL(16, 150, 12, 0),
QT_MOC_LITERAL(17, 163, 12, 0),
QT_MOC_LITERAL(18, 176, 12, 0),
QT_MOC_LITERAL(19, 189, 12, 0),
QT_MOC_LITERAL(20, 202, 19, 0),
QT_MOC_LITERAL(21, 222, 19, 0),
QT_MOC_LITERAL(22, 242, 7, 0),
QT_MOC_LITERAL(23, 250, 31, 0),
QT_MOC_LITERAL(24, 282, 17, 0),
QT_MOC_LITERAL(25, 300, 21, 0),
QT_MOC_LITERAL(26, 322, 17, 0),
QT_MOC_LITERAL(27, 340, 12, 0),
QT_MOC_LITERAL(28, 353, 12, 0),
QT_MOC_LITERAL(29, 366, 10, 0),
QT_MOC_LITERAL(30, 377, 15, 0),
QT_MOC_LITERAL(31, 393, 12, 0),
QT_MOC_LITERAL(32, 406, 11, 0),
QT_MOC_LITERAL(33, 418, 9, 0),
QT_MOC_LITERAL(34, 428, 12, 0),
QT_MOC_LITERAL(35, 441, 23, 0),
QT_MOC_LITERAL(36, 465, 10, 0),
QT_MOC_LITERAL(37, 476, 17, 0),
QT_MOC_LITERAL(38, 494, 11, 0),
QT_MOC_LITERAL(39, 506, 25, 0),
QT_MOC_LITERAL(40, 532, 12, 0),
QT_MOC_LITERAL(41, 545, 27, 0)
    },
    "RealSvrOcxTcpLib::_DRealSvrOcxTcp\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0AboutBox\0CloseNetwork\0anHostPort\0OpenNetwork\0SendResponse\0"
    "astrClientIP\0anClientPort\0astrResponse\0SendRtLogResponseV1\0SendRtLogResponseV3\0"
    "control\0RealSvrOcxTcpLib::RealSvrOcxTcp\0Event Interface 1\0_DRealSvrOcxTcpEvents\0"
    "OnReceiveGLogData\0astrDeviceIP\0anDevicePort\0anDeviceID\0anSEnrollNumber\0"
    "anVerifyMode\0anInOutMode\0anLogDate\0astrSerialNo\0OnReceiveGLogDataExtend\0"
    "astrRootIP\0OnReceiveGLogText\0astrLogText\0OnReceiveGLogTextAndImage\0astrLogImage\0"
    "OnReceiveGLogTextOnDoorOpen\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_RealSvrOcxTcpLib___DRealSvrOcxTcp[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    9, 14, // methods
    1, 106, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 59, 2, 5,
    7, 1, 68, 2, 5,
    9, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 78, 2, 9,
    13, 1, 79, 2, 9,
    15, 1, 82, 2, 9,
    16, 3, 85, 2, 9,
    20, 3, 92, 2, 9,
    21, 3, 99, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 19,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 19,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 19,

 // properties: name, type, flags
    22, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DRealSvrOcxTcp::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_RealSvrOcxTcpLib___DRealSvrOcxTcp, 0, 0, 0 }
};

void *_DRealSvrOcxTcp::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "RealSvrOcxTcpLib::_DRealSvrOcxTcp"))
        return static_cast<void*>(const_cast<_DRealSvrOcxTcp*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_RealSvrOcxTcpLib__RealSvrOcxTcp[] = {

 // content:
    7, // revision
    23,  // classname
    1, 14, // classinfo
    14, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    8, // signal count

 // classinfo: key, value
    24, 25, 

// signal: name, argc, parameters, tag, flags
    26, 8, 86, 2, 5,
    35, 9, 103, 2, 5,
    37, 3, 122, 2, 5,
    39, 4, 129, 2, 5,
    41, 4, 138, 2, 5,
    1, 4, 147, 2, 5,
    7, 1, 156, 2, 5,
    9, 3, 159, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 166, 2, 9,
    13, 1, 167, 2, 9,
    15, 1, 170, 2, 9,
    16, 3, 173, 2, 9,
    20, 3, 180, 2, 9,
    21, 3, 187, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QDateTime, QMetaType::QString, 27, 28, 29, 30, 31, 32, 33, 34,
    QMetaType::Void, QMetaType::QString, QMetaType::QString, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::Int, QMetaType::QDateTime, QMetaType::QString, 36, 27, 28, 29, 30, 31, 32, 33, 34,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 38,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, 17, 18, 38, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::QString, QMetaType::QString, 17, 18, 38, 40,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::Int, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 19,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 19,
    QMetaType::Int, QMetaType::QString, QMetaType::Int, QMetaType::QString, 17, 18, 19,

    0 // eod
};

const QMetaObject RealSvrOcxTcp::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_RealSvrOcxTcpLib__RealSvrOcxTcp, 0, 0, 0 }
};

void *RealSvrOcxTcp::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "RealSvrOcxTcpLib::RealSvrOcxTcp"))
        return static_cast<void*>(const_cast<RealSvrOcxTcp*>(this));
    return QAxWidget::qt_metacast(_clname);
}

